
import getpass
import glob
import json
import os
import re
import logging
import asyncio
import aiofiles
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate
import numpy as np
from pydantic import BaseModel, Field, SecretStr
from sklearn.metrics.pairwise import cosine_similarity
import sys
from typing import List

class triplet(BaseModel):
    start_node: str = Field(description='start biological entity of the viewpoint')
    relation: str = Field(description='The causal relation between the biological entities')
    end_node: str = Field(description='end biological entity of the viewpoint')

class Viewpoint(BaseModel):
    viewpoints: List[triplet] = Field(description="The list of the viewpoint between two biological entities")

class Evaluator(BaseModel):
    Analysis: str = Field(description="Comparison between the two hypotheses")
    Choice: int = Field(description="Preference of the two hypotheses")


class RefinedHypothesis(BaseModel):
    CausalChain: str = Field(description='Causal chain of the hypothesis. Use -> represent the causal relationship.')
    Hypothesis: str = Field(
        description="specific content of the hypothesis"
    )
    Abstract: str = Field(
        description="hypothesis converted to paper abstract format, The format should be as close to the Abstract section of a scientific article as possible."
    )
    Orignal_vs_New:str = Field(
         description="The changes of the new one to the original one."
    )


class Hypothesis(BaseModel):
    # think: Optional[str] = Field(description="COT of the model")
    CausalChain: str = Field(description='Causal chain of the hypothesis. Use -> represent the causal relationship.')
    RegulatoryRelationshipAnalysis: str = Field(
        description="bioinformatics statistical analysis and reasoning process. According to the bioinformatics statistical results we provide, analyze the regulatory relationship between genes, functional profiling and cancer.")
    Hypothesis: str = Field(
        description="specific content of the hypothesis"
    )
    Abstract: str = Field(
        description="hypothesis converted to paper abstract format, The format should be as close to the Abstract section of a scientific article as possible."
    )

class Review_Hypothesis(BaseModel):
    # think: Optional[str] = Field(description="COT of the model")
    CausalChain: str = Field(description='Causal chain of the hypothesis. Use -> represent the causal relationship.')
    Hypothesis: str = Field(
        description="specific content of the hypothesis"
    )
    Abstract: str = Field(
        description="hypothesis converted to paper abstract format, The format should be as close to the Abstract section of a scientific article as possible."
    )

class AI_Hypothesis:
    def __init__(self,triple : dict, num_hypothethesis:int, save_path:str, knowledge_path:str, 
    chatModel='chatgpt-4o-latest', embeddingModel='text-embedding-3-small'):
        '''
        triple: triplet generated by XAI
        epochs: number of iterations for evolution
        number_hypothethesis: number of hypothethesis for generate
        save_path: save the model respond to the path.
        
        '''
        self.n_ask = num_hypothethesis
        self.triple = triple
        
        if not os.environ.get("OPENAI_API_KEY"):
            os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter API key for OpenAI: ")
        if not os.environ.get("BASE_URL"):
            os.environ["BASE_URL"] = getpass.getpass("Enter BASE URL: ")
        os.makedirs(save_path, exist_ok=True)
        self.chatModel = ChatOpenAI(model=chatModel, api_key=SecretStr(os.environ["OPENAI_API_KEY"]), base_url=os.environ["BASE_URL"], timeout=120, max_retries=3)
        self.embeddingModel = OpenAIEmbeddings(model=embeddingModel, api_key=SecretStr(os.environ["OPENAI_API_KEY"]), base_url=os.environ["BASE_URL"], timeout=120, max_retries=3)
        self.generation_agent = GenerationAgent(self.chatModel)
        self.review_genagent = FullTextHypothesisAgent(self.chatModel)
        self.proximity_agent = ProximityAgent(self.embeddingModel)
        self.ranking_agent = RankingAgent(self.chatModel)
        self.reflection_agent = ReflectionAgent(self.chatModel)
        self.truth_loom = TruthLoom(self.chatModel)
        self.evo_agent = EvolutionAgent(self.chatModel)
        self.decomposer_agent = DecomposerAgent(self.chatModel)

        self.knowledge_path = knowledge_path
        self.save_path = save_path
        logging.basicConfig(
           level=logging.INFO,  # 设置日志级别为 INFO
            format='%(asctime)s - %(levelname)s - %(message)s',  # 设置日志格式
            handlers=[logging.StreamHandler()]  # 输出到控制台
        )

    async def internal_trial_system(self):
        # Generate initial content and build candidates with their original index concurrently
        general_content = await self.generation_agent.generate(self.triple, self.n_ask, self.save_path)
        # general_content = await self.review_genagent.generate(self.triple, self.n_ask, self.save_path)
        candidates = []
        for i, content in enumerate(general_content):
            candidates.append({
                "seed_index": i,
                "Hypothesis": content.Hypothesis,
                "Abstract": content.Abstract,
                "CausalChain": content.CausalChain
            })

        current_candidates = candidates
        round_counter = 1

        # Define an async helper to process a group of candidates concurrently
        async def process_group(group, round_counter):
            round_path = os.path.join(self.save_path, f'round{round_counter}')
            # Extract abstracts for the group and query similar abstracts
            group_abstracts = [current_candidates[i]["Abstract"] for i in group]
            logging.info('start query similar abstracts')
            top_results = similar_abstracts(group_abstracts, self.embeddingModel, self.knowledge_path, 3)

            # For each candidate in the group, concurrently obtain reflection reviews and aggregate them
            async def process_candidate(j, idx):
                orig_idx = current_candidates[idx]["seed_index"]
                logging.info(f'start review for candidate {orig_idx}')
                observe_task = await self.reflection_agent.observe(
                    [item['abstract'] for item in top_results[j]],
                    current_candidates[idx]["Hypothesis"],
                    orig_idx,
                    round_path
                )
                review_task_omics = await self.reflection_agent.review(
                    current_candidates[idx]["Hypothesis"],
                    'omics',
                    orig_idx,
                    round_path
                )
                review_task_cellular = await self.reflection_agent.review(
                    current_candidates[idx]["Hypothesis"],
                    'cellular biology',
                    orig_idx,
                    round_path
                )
                review_task_clinical = await self.reflection_agent.review(
                    current_candidates[idx]["Hypothesis"],
                    'clinical research',
                    orig_idx,
                    round_path
                )
                # Run all reflection tasks in parallel
                reviews = [observe_task, review_task_omics, review_task_cellular, review_task_clinical]
                agg = self.truth_loom.wrapup(reviews, orig_idx, round_path)
                return orig_idx, reviews, agg

            candidate_tasks = [process_candidate(j, idx) for j, idx in enumerate(group)]
            candidate_results = await asyncio.gather(*candidate_tasks)

            # Build the aggregated review list for the group in the original candidate order
            agg_rev = {res[0]: res[2] for res in candidate_results}

            group_hyps = [current_candidates[i]["Hypothesis"] for i in group]
            group_rev_list = [agg_rev[current_candidates[i]["seed_index"]] for i in group]
            logging.info('start PK ...')
            if len(group) == 2:
                winner_idx = self.ranking_agent.PK(
                    group_hyps,
                    group_rev_list,
                    [current_candidates[i]['seed_index'] for i in group],
                    round_path
                )
            else:
                winner_idx = [current_candidates[i]['seed_index'] for i in group][0]

            winner_candidate = next(candidate for candidate in current_candidates if candidate["seed_index"] == winner_idx)

            winner_reviews = next(item[1] for item in candidate_results if item[0] == winner_idx)
            logging.info('start evolve ...')
            evolved_winner = self.evo_agent.evolve(
                winner_candidate["Hypothesis"],
                winner_candidate["CausalChain"],
                winner_reviews,
                winner_candidate["seed_index"],
                round_path
            )
            
            return {
                "seed_index": winner_candidate["seed_index"],
                "Hypothesis": evolved_winner.Hypothesis,
                "Abstract": evolved_winner.Abstract,
                "CausalChain": evolved_winner.CausalChain
            }

        # Continue tournament rounds until only one candidate remains, processing groups in parallel
        while len(current_candidates) > 1:
            logging.info(f'start round {round_counter}')
            logging.info('start group by similarity')
            grouped_indices = self.proximity_agent.group_by_similarity(
                [cand["Hypothesis"] for cand in current_candidates]
            )
            group_tasks = [process_group(group, round_counter) for group in grouped_indices]
            next_round_candidates = await asyncio.gather(*group_tasks)
            current_candidates = next_round_candidates
            round_counter += 1

        # Save the final champion(s) with their original indices
        final_winner_file = os.path.join(self.save_path, "champion.json")
        with open(final_winner_file, "w") as f:
            json.dump(current_candidates, f, indent=4, ensure_ascii=False)
        
        viewpoints = await self.decomposer_agent.decompose(current_candidates, self.save_path)

        logging.info('process end')
        return current_candidates


class FullTextHypothesisAgent():
    def __init__(self, model):
        self.model = model.with_structured_output(Review_Hypothesis)
        self.system_prompt = '''
You are given the full text of a biomedical review article. Your task is to carefully analyze the content and, based on the information and reasoning within the review, generate a novel biological hypothesis. The hypothesis should be original, plausible, and not a mere restatement of known facts from the review. Additionally, construct a CausalChain that logically connects biological entities, mechanisms, or processes described in the review to support your hypothesis.

Output format (in JSON):
{
"CausalChain": "Insert the logical causal inference chain here, showing the stepwise biological reasoning that leads to your hypothesis.",
"Hypothesis": "State your novel biological hypothesis here, clearly and concisely."
}

Guidelines:
- The hypothesis must be novel and not simply repeat conclusions from the review.
- The CausalChain should be explicit, stepwise, and based on mechanisms or relationships discussed in the review.
- Do not include statistical data or direct quotations from the review.
- Ensure the hypothesis is biologically plausible and testable.
        '''

    async def generate(self, md: str, n_ask: int, path):
        self.path = os.path.join(path, 'generate_hypotheses')
        os.makedirs(self.path, exist_ok=True)
        tasks = []
        for idx in range(n_ask):
            tasks.append(self._process_single(md, idx))
        results = await asyncio.gather(*tasks)
        return results

    async def _process_single(self, md: str, idx: int):
        messages = [
            SystemMessage(self.system_prompt),
            HumanMessage(md)
        ]
        save_path = os.path.join(self.path, f'{idx}.json')
        if not os.path.exists(save_path):
            AIMessage = await self.model.ainvoke(messages)
            await self.save(AIMessage, idx)
        else:
            async with aiofiles.open(save_path, 'r', encoding='utf-8') as f:
                content = await f.read()
                AIMessage = json.loads(content)
                # AIMessage = Hypothesis(**AIMessage)
                AIMessage = Review_Hypothesis(**AIMessage)
        return AIMessage

    async def save(self, message, index):
        async with aiofiles.open(os.path.join(self.path, f'{index}.json'), 'w', encoding='utf-8') as f:
            await f.write(message.model_dump_json( indent=4))
        
class GenerationAgent():
    def __init__(self, model):
        self.model = model.with_structured_output(Hypothesis)
        self.system_prompt = f'''
I have provided a bioinformatics statistical information between a gene, a functional module (if any) and cancer in the "Information provided". Please note that this information is only obtained through model calculation and manual calculation, and has not been verified by wet laboratory experiments.
First, I need you to analyze the regulatory relationship between the gene, the functional module and the cancer prognosis based on this information, and insert the analysis results into the "Regulatory relationship analysis" section. Second, propose a novel scientific hypothesis based on the regulatory relationship you analyzed, and Insert the generated results into the "Hypothesis" section. Third, I need you to convert the hypothesis you just generated into a scientific article abstract format and insert the results into the "Abstract" section.

Note that the "Hypothesis" and “Abstract” sections needs to meet the following conditions:
a. The content cannot contain bioinformatics statistics data.
b. Other genes besides the gene we provide can be hypothesized, but you must explain how these genes (including the gene we provide) interact with each other and how they affect the activation or inhibition of the functional module we provide;
c. Detailed explanation of how the upregulation or downregulation of genes may affect the activation or inhibition of the functional module; (such as  enzyme activity, signal regulation, etc.)
d. Detailed explanation of how the activation and inhibition of the functional module affect the prognosis of cancer (such as metastasis or angiogenesis);
e. The hypothesis can be interpreted in combination with known research results, but the novelty of the hypothesis must be ensured at the same time.

The CausalChain presents the logical relationship among biology ontologies.
The format of outputs:
' CausalChain: "Insert the causal inference chain here for the hypothesis."
· Regulatory relationship analysis: "Insert bioinformatics statistical analysis and reasoning process. According to the bioinformatics statistical results we provide, analyze the regulatory relationship between genes, functional modules and cancer."
· Hypothesis: "Insert the specific content of the hypothesis here."
· Abstract: " Insert hypothesis converted to paper abstract format,The format should be as close to the Abstract section of a scientific article as possible."
output in json format.
        '''
        
        
        
        


    async def generate(self, triple: dict, n_ask: int, path):
        self.path = os.path.join(path, 'generate_hypotheses')
        os.makedirs(self.path, exist_ok=True)
        tasks = []
        for idx in range(n_ask):
            tasks.append(self._process_single(triple, idx))
        results = await asyncio.gather(*tasks)
        return results

    async def _process_single(self, triple: dict, idx: int):
        messages = [
            SystemMessage(self.system_prompt),
            HumanMessage(json.dumps(triple))
        ]
        save_path = os.path.join(self.path, f'{idx}.json')
        if not os.path.exists(save_path):
            AIMessage = await self.model.ainvoke(messages)
            await self.save(AIMessage, idx)
        else:
            async with aiofiles.open(save_path, 'r', encoding='utf-8') as f:
                content = await f.read()
                AIMessage = json.loads(content)
                AIMessage = Hypothesis(**AIMessage)
        return AIMessage

    async def save(self, message, index):
        async with aiofiles.open(os.path.join(self.path, f'{index}.json'), 'w', encoding='utf-8') as f:
            await f.write(message.model_dump_json(indent=4))
    

class ProximityAgent():
    def __init__(self, model) -> None:
        self.model = model

    def group_by_similarity(self, hypotheses):
        '''
        Args:
            hypotheses (List[str]): 待分组的假设列表。

        Returns:
            List[List[str]]: 分组后的假设列表，每组包含2个假设。
        '''
        retry_count = 0
        embeddings = None
        while retry_count < 10:
            try:
                embeddings = self.model.embed_documents(hypotheses)
                if embeddings is not None:
                    break
            except TypeError as e:
                if "'NoneType' object is not iterable" in str(e):
                    retry_count += 1
                    continue
                else:
                    raise
            except Exception as e:
                retry_count += 1
                continue
        if embeddings is None:
            raise RuntimeError("Failed to get embeddings after 5 retries.")
        embeddings = np.array(embeddings)
        similarity_matrix = cosine_similarity(embeddings)
        np.fill_diagonal(similarity_matrix, -np.inf)
        ungrouped_indices = set(range(len(hypotheses)))
        groups = []
        while len(ungrouped_indices) >= 2:
            idx_a, idx_b = np.unravel_index(np.argmax(similarity_matrix), similarity_matrix.shape)
            idx_a, idx_b = int(idx_a), int(idx_b)
            # 添加分组
            groups.append([{idx_a:hypotheses[idx_a]}, {idx_b: hypotheses[idx_b]}])
            # 移除已分组的索引
            ungrouped_indices.remove(idx_a)
            ungrouped_indices.remove(idx_b)
            # 更新相似度矩阵，避免再次使用已经分组的成员
            similarity_matrix[idx_a, :] = -np.inf
            similarity_matrix[:, idx_a] = -np.inf
            similarity_matrix[idx_b, :] = -np.inf
            similarity_matrix[:, idx_b] = -np.inf

        # 若剩余单个成员，单独成组
        if ungrouped_indices:
            remaining_idx = ungrouped_indices.pop()
            groups.append([{remaining_idx:hypotheses[remaining_idx]}])

        return [[key for j in i for key in j.keys()] for i in groups ]


def similar_abstracts(abstracts, embedding_model, knowledge_path, top_n):
    '''
    abstract: abstract to compare with pubmed
    path: path of pubmed embedding
    '''
    vector_store = Chroma(
        collection_name="HCC_pubmed_abstracts",
        embedding_function=embedding_model,
        persist_directory=knowledge_path,  # Where to save data locally, remove if not necessary
    )
    top_results = {}
    for _, abs in enumerate(abstracts):
        retry_count = 0
        result = None
        while retry_count < 3:
            try:
                result = vector_store.similarity_search_with_score(abs, top_n)
                if result is not None:
                    break
            except Exception as e:
                pass
            retry_count += 1
        if result is None:
            top_results[_] = []
            continue
        top_results[_] = [
            {'pid': i[0].id, 'similarity': 1 - i[1], 'abstract': i[0].page_content}
            for i in result if i is not None
        ]
    return top_results

class RankingAgent():
    def __init__(self, chatModel) -> None:
        self.chatModel = chatModel.with_structured_output(Evaluator)
        self.internal_pk_template = ChatPromptTemplate([
            ('system', '''You are an expert evaluator tasked with comparing two hypotheses.
Evaluate the two provided hypotheses (hypothesis 1 and hypothesis 2) and determine which one
is superior based on the the novelty, plausibility, testability and safety.
Provide a concise rationale for your selection, concluding with the phrase "better idea: <1 or 2>".
Evaluation criteria:
1. novelty
2. plausibility
3. testability
4. safety
Considerations:
{notes}
Each hypothesis includes an independent review.These reviews may contain numerical scores.
Disregard these scores in your comparative analysis, as they may not be directly comparable across reviews.'''),
            ('user', '''
Hypothesis 1:
{hypothesis1}
Hypothesis 2:
{hypothesis2}
Review of hypothesis 1:
{review1}
Review of hypothesis 2:
{review2}
Reasoning and conclusion (end with "better hypothesis: <1 or 2>"):
             ''')
        ])

    def PK(self, hypotheses, reviews, group_index, path):
        self.save_path = os.path.join(path, 'PK')
        os.makedirs(self.save_path, exist_ok=True)
        messages = self.internal_pk_template.invoke({
            'hypothesis1': hypotheses[0],
            'hypothesis2': hypotheses[1],
            'review1': reviews[0],
            'review2': reviews[1],
            'notes': None
        })
        save_path = f'{self.save_path}/{group_index[0]}vs{group_index[1]}.json'
        if not os.path.exists(save_path):
            response = self.chatModel.invoke(messages)

            with open(save_path, 'w', encoding='utf-8') as f:
                f.write(response.model_dump_json(indent=4))
            
        else:
            with open(save_path, 'r', encoding='utf-8') as f:
                response = Evaluator(**json.load(f))
                
        return group_index[response.Choice-1]

class EvolutionAgent:
    def __init__(self, model) -> None:
        self.model = model.with_structured_output(RefinedHypothesis)
        self.review_template = ChatPromptTemplate([
            ('system', ''' You are an expert in scientific research. Based on the following review comments, revise the original 
hypothesis to better align with the observed evidence in studies. In addition, enhance its practical implementability
by leveraging contemporary technological capabilities. Ensure the revised concept retains
its novelty, logical coherence, and specific articulation. Your new hypothesis **MUST** explicitly reflect, incorporate, or reference elements from the original hypothesis and causal chain. 
Clearly explain how the new hypothesis relates back to each critical step of the original causal reasoning.
do NOT forget the causal steps'''),
            ('user', '''
            Original causal chain:
            {CausalChain}
            Original hypothesis:
            {hypothesis}
            review:
            {review}
            Response:
            ''')
            
        ])
        self.feasibility_template = ChatPromptTemplate([
            ('system', '''You are an expert in scientific research and technological feasibility analysis.
Your task is to refine the provided conceptual idea, enhancing its practical implementability
by leveraging contemporary technological capabilities. Ensure the revised concept retains
its novelty, logical coherence, and specific articulation.
Guidelines:
1. Begin with an introductory overview of the relevant scientific domain.
2. Provide a concise synopsis of recent pertinent research findings and related investigations,
highlighting successful methodologies and established precedents.
3. Articulate a reasoned argument for how current technological advancements can facilitate
the realization of the proposed concept.
4. CORE CONTRIBUTION: Develop a detailed, innovative, and technologically viable alternative
to achieve the objective, emphasizing simplicity and practicality.
'''), 
        ('user', '''Original Conceptualization:
{hypothesis}
Response:
         ''')
        ])
        self.out_of_box_thinking_template = ChatPromptTemplate([
            ('system', '''You are an expert researcher tasked with generating a novel, singular hypothesis
inspired by analogous elements from provided concepts.
Instructions:
1. Provide a concise introduction to the relevant scientific domain.
2. Summarize recent findings and pertinent research, highlighting successful approaches.
3. Identify promising avenues for exploration that may yield innovative hypotheses.
4. CORE HYPOTHESIS: Develop a detailed, original, and specific single hypothesis.
for achieving the stated goal, leveraging analogous principles from the provided
ideas. This should not be a mere aggregation of existing methods or entities. Think out-of-the-box.
Criteria for a robust hypothesis:
             Focus on providing a novel hypothesis, with detailed explanation of the mechanism of action'''),
             ('user', '''
Inspiration may be drawn from the following concepts (utilize analogy and inspiration,
not direct replication):
{hypothesis}
Response:
''')
        ])
        

    def evolve(self, hypothesis, causalChain, review, group_index, path):
        # Define the save file path using the group index as the filename
        self.save_path = path
        save_dir = os.path.join(self.save_path, "evolved_hypotheses")
        os.makedirs(save_dir, exist_ok=True)
        save_file = os.path.join(save_dir, f"{group_index}.json")
        
        # If the final hypothesis exists, load and return it directly
        if os.path.exists(save_file):
            with open(save_file, 'r', encoding='utf-8') as f:
                saved_hypothesis = json.load(f)
            return RefinedHypothesis(**saved_hypothesis)
        
        # Otherwise, generate the final hypothesis
        evo0 = self.review_template.invoke({'hypothesis': hypothesis, 'review': review, 'CausalChain': causalChain})
        res0 = self.model.invoke(evo0)
        
        # evol1 = self.feasibility_template.invoke({'hypothesis': res0.Hypothesis})
        # res1 = self.model.invoke(evol1)
        
        # evol2 = self.out_of_box_thinking_template.invoke({'hypothesis': res1.Hypothesis})
        # res2 = self.model.invoke(evol2)
        
        # Save the generated hypothesis with the group index as its name
        # Using model_dump() if available, otherwise the __dict__
        result_data = res0.model_dump() if hasattr(res0, "model_dump") else res0.__dict__
        with open(save_file, 'w') as f:
            json.dump(result_data, f, indent=4, ensure_ascii=False)
            
        return res0

class ReflectionAgent:
    def __init__(self, model) -> None:
        self.model = model
        self.review_template = ChatPromptTemplate([
            ('system', '''
You are an expert in {specialist}, Your task is to provide a thorough and critical analysis, ensuring accuracy, rigor, 
and clarity in your hypothesis evaluation.
Please perform the following steps sequentially:
Hypothesis Summary: Concisely summarize the main idea and key components of the hypothesis.
Originality Assessment: Evaluate whether this hypothesis is original within your field. Does it offer innovative perspectives or distinguish itself from existing studies or established knowledge?
Validity and Strength Evaluation: Critically assess the logical coherence and strength of the relationship suggested by the hypothesis. Consider whether the reasoning is explicit, logically sound, and supported by sufficient evidence or theoretical grounding.
Conclusion and Expert Recommendations: Explicitly state whether there are any notable weaknesses or gaps in this hypothesis. If identified, clearly pinpoint their location within the hypothesis and provide concrete, actionable suggestions to enhance the hypothesis’s scientific rigor and persuasive power.
             '''),
             ('user', '''
Hypothesis:
{hypothesis}
              ''')
        ])
        self.observe_template = ChatPromptTemplate([
            ('system', '''
You are an expert in scientific hypothesis evaluation. Your task is to analyze the
relationship between a provided hypothesis and observations from the similar abstracts.
Specifically, determine if the hypothesis provides a novel causal explanation
for the observations, or if they contradict it.
Instructions:
1. Observation extraction: list relevant observations from the abstracts.
2. Causal analysis (individual): for each observation:
a. State if its cause is already established.
b. Assess if the hypothesis could be a causal factor (hypothesis => observation).
c. Start with: "would we see this observation if the hypothesis was true:".
d. Explain if it’s a novel explanation. If not, or if a better explanation exists,
state: "not a missing piece."
3. Causal analysis (summary): determine if the hypothesis offers a novel explanation
for a subset of observations. Include reasoning. Start with: "would we see some of
the observations if the hypothesis was true:".
4. Disproof analysis: determine if any observations contradict the hypothesis.
Start with: "does some observations disprove the hypothesis:".
5. Conclusion: state: "hypothesis: <already explained, other explanations more likely,
missing piece, neutral, or disproved>".
Scoring:
* Already explained: hypothesis consistent, but causes are known. No novel explanation.
* Other explanations more likely: hypothesis *could* explain, but better explanations exist.
* Missing piece: hypothesis offers a novel, plausible explanation.
* Neutral: hypothesis neither explains nor is contradicted.
* Disproved: observations contradict the hypothesis.
Important: if observations are expected regardless of the hypothesis, and don’t disprove it,
'''),
            ('user', """
top 3 abstract:
{abstracts}
Hypothesis:
{hypothesis}
Response: provide reasoning. end with: "hypothesis: <already explained, other explanations
more likely, missing piece, neutral, or disproved>".)
                         """)
        ])
    async def observe(self, top_abstract, hypothesis, group_index, path):
        # Combine the top abstracts into a single string
        self.save_path = os.path.join(path, f'observation')
        abstracts_text = "\n".join(top_abstract)
        
        # Get response using the observe template
        messages = self.observe_template.invoke({
            "abstracts": abstracts_text,
            "hypothesis": hypothesis
        })
        # Define the response file path
        response_file = os.path.join(self.save_path, f"{group_index}.md")
        
        if os.path.exists(response_file):
            # Load existing response asynchronously
            async with aiofiles.open(response_file, 'r') as f:
                response_content = await f.read()
            response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response_content)
            return response_content
        
        # Get new response asynchronously
        response = await self.model.ainvoke(messages)
        
        # Save response asynchronously
        os.makedirs(self.save_path, exist_ok=True)
        async with aiofiles.open(response_file, 'w') as f:
            await f.write(response.content)
        response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response.content)
        return response_content

    async def review(self, hypothesis, specialist, group_index, path):
        """
        Generate a review analysis by combining provided review texts with the hypothesis.
        This function is analogous to the 'observe' method but uses a different prompt template.
        """
        # Combine the provided reviews into a single string
        self.save_path = os.path.join(path, "review")
        
        # Get response using the review template
        messages = self.review_template.invoke({
            "hypothesis": hypothesis,
            "specialist": specialist
        })
        
        # Define a file to cache the response for the given group index
        response_file = os.path.join(self.save_path, f"{specialist}_{group_index}.md")
        
        if os.path.exists(response_file):
            # Load existing response asynchronously
            async with aiofiles.open(response_file, "r") as f:
                response_content = await f.read()
            response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response_content)
            return response_content
        
        # Get new response from the model asynchronously
        response = await self.model.ainvoke(messages)
        
        # Ensure the directory exists and save the response asynchronously
        os.makedirs(self.save_path, exist_ok=True)
        async with aiofiles.open(response_file, "w") as f:
            await f.write(response.content)
        
        response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response.content)
        return  response_content
    
class TruthLoom:
    def __init__(self, model) -> None:
        self.model = model
        self.template = ChatPromptTemplate([
            ('system', '''You are an expert in scientific research and meta-analysis.
Synthesize a comprehensive meta-review of provided reviews
pertaining to the following research goal:
Preferences:
Focus on providing a novel hypothesis, with detailed explanation of the mechanism of action


            '''),
            ('user', '''Provided reviews for meta-analysis:
{reviews}   
Instructions:
* Generate a structured meta-analysis report of the provided reviews.
* Focus on identifying recurring critique points and common issues raised by reviewers.
* The generated meta-analysis should provide actionable insights for researchers
developing future proposals.
* Refrain from evaluating individual proposals or reviews;
focus on producing a synthesized meta-analysis.
Response:
            ''')
        ])

    def wrapup(self, reviews:list, group_index:int, path):

        messages = self.template.invoke({
            'reviews': '\n'.join([f'reviews{i}:\n{j} ' for i, j in enumerate(reviews)]),
        })
        response_file = os.path.join(path, f"wrapup_{group_index}.md")
        if os.path.exists(response_file):
            with open(response_file, 'r') as f:
                response_content = f.read()
            response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response_content)
            return response_content
        response = self.model.invoke(messages)
        os.makedirs(path, exist_ok=True)
        with open(response_file, 'w') as f:
            f.write(response.content)
        response_content = re.sub(r"<think>\n[\s\S]*?</think>\n", "", response.content)
        return response_content

class DecomposerAgent:
    def __init__(self, model) -> None:
        # The model is assumed to support asynchronous invocation with structured messages.
        self.model = model.with_structured_output(Viewpoint)
        self.decompose_template = ChatPromptTemplate([
            ('system','''You are a scientific researcher with expertise in decomposing complex biological hypotheses into precise, granular viewpoints for systematic evaluation.
Your task is to:
1. **Decompose** the provided hypothesis into multiple clearly defined viewpoints.
2. Each viewpoint must explicitly include:
   - A pair of biological entities.
   - A clearly stated causal relationship connecting these two entities.
   - Do not use passive voice.
Guidelines for decomposition:
- **Independence**: Ensure each viewpoint is as independent and distinct as possible, minimizing overlap or interdependence.
- **Granularity**: Select biological ontologies and causal relationships at the most granular level possible, such that viewpoints cannot reasonably be decomposed further.
- **Completeness**: Ensure all essential and core perspectives within the original hypothesis are comprehensively covered, without omission.


Proceed carefully to maintain scientific rigor and clarity.


'''),
                
            ('user', '''
Hypothesis: {champion}
             ''')])
        self.decompose_full_text_template = ChatPromptTemplate([
                    ('system','''You are a scientific researcher with expertise in decomposing complex biological paper into precise, granular viewpoints for systematic evaluation.
        Your task is to:
        1. **Decompose** the provided abstracts into multiple clearly defined viewpoints.
        2. Each viewpoint must explicitly include:
        - A pair of biological entities.
        - A clearly stated causal relationship connecting these two entities.

                    
        Guidelines for decomposition:
        - **Independence**: Ensure each viewpoint is as independent and distinct as possible, minimizing overlap or interdependence.
        - **Granularity**: Select biological ontologies and causal relationships at the most granular level possible, such that viewpoints cannot reasonably be decomposed further.
        - **Completeness**: Ensure all essential and core perspectives within the original hypothesis are comprehensively covered, without omission.


        Proceed carefully to maintain scientific rigor and clarity.


        '''),   
                    ('user', '''
Hypothesis: {champion}
             ''')]) 
        self.novel_viewpoint_template = ChatPromptTemplate([
                    ('system','''You are a scientific researcher with expertise in propose novel biological precise, granular viewpoints for systematic evaluation.
        Your task is to:
        1. Propose multiple clear, well defined, novel viewpoints that are not delved into at all. 
        2. Each viewpoint must explicitly include:
        - A pair of biological entities.
        - A clearly stated causal relationship connecting these two entities.

                    
        Guidelines for decomposition:
        - **Independence**: Ensure each viewpoint is as independent and distinct as possible, minimizing overlap or interdependence.
        - **Granularity**: Select biological ontologies and causal relationships at the most granular level possible, such that viewpoints cannot reasonably be decomposed further.
        - **Completeness**: Ensure all essential and core perspectives within the original hypothesis are comprehensively covered, without omission.each proposed viewpoint adheres to the logical sequence and relationships outlined in the causal chain.


        Proceed carefully to maintain scientific rigor and clarity.


        '''),   
                    ('user', '''
Hypothesis: {champion}
             ''')]) 
        
    async def decompose(self, champion_hypothesis: list, path:str) -> str:
        """
        Decomposes the champion hypothesis into multiple viewpoints.
        Args:
            champion_hypothesis (dict): The champion hypothesis with keys such as 'Hypothesis', 'Abstract', and 'CausalChain'.
        Returns:
            list: A list of decomposed viewpoints (each being a causal chain string or structured object).
        """


        messages = self.decompose_template.invoke(
            {
                'champion': champion_hypothesis[0]['Hypothesis']
            }
        )
        response_file = os.path.join(path, f"viewpoints.json")
        
        if os.path.exists(response_file):
            # Load existing response asynchronously
            async with aiofiles.open(response_file, "r") as f:
                response_content = await f.read()
            return response_content
        
        # Get new response from the model asynchronously
        response = await self.model.ainvoke(messages)
        
        # Ensure the directory exists and save the response asynchronously
        os.makedirs(path, exist_ok=True)
        async with aiofiles.open(response_file, "w", encoding='utf-8') as f:
            await f.write(response_content:=response.model_dump_json(indent=4))
        
        return  response_content
    
    async def decompose_abstract(self, abstract: str, path:str) -> str:
        """
        Decomposes the abstract into multiple viewpoints.
        Args:
            abstract (str): The abstract of an article.
        Returns:
            list: A list of decomposed viewpoints (each being a causal chain string or structured object).
        """


        messages = self.decompose_full_text_template.invoke(
            {
                'champion': abstract
            }
        )
        response_file = os.path.join(path, f"viewpoints.json")
        
        if os.path.exists(response_file):
            # Load existing response asynchronously
            async with aiofiles.open(response_file, "r") as f:
                response_content = await f.read()
            return response_content
        
        # Get new response from the model asynchronously
        response = await self.model.ainvoke(messages)
        
        # Ensure the directory exists and save the response asynchronously
        os.makedirs(path, exist_ok=True)
        async with aiofiles.open(response_file, "w", encoding='utf-8') as f:
            await f.write(response_content:=response.model_dump_json(indent=4))
        
        return  response_content

    async def novel_viewpoint(self, full_text: str, path:str) -> str:
        """
        propose novel viewpoint from the review.
        Args:
            full_text (str): The abstract of an article.
        Returns:
            list: A list of decomposed viewpoints (each being a causal chain string or structured object).
        """


        messages = self.decompose_full_text_template.invoke(
            {
                'champion': full_text
            }
        )
        response_file = os.path.join(path, f"viewpoints.json")
        
        if os.path.exists(response_file):
            # Load existing response asynchronously
            async with aiofiles.open(response_file, "r") as f:
                response_content = await f.read()
            return response_content
        
        # Get new response from the model asynchronously
        response = await self.model.ainvoke(messages)
        
        # Ensure the directory exists and save the response asynchronously
        os.makedirs(path, exist_ok=True)
        async with aiofiles.open(response_file, "w", encoding='utf-8') as f:
            await f.write(response_content:=response.model_dump_json(indent=4))
        
        return  response_content



def _main():
    with open(sys.argv[1]) as f:
        triplets = json.load(f)
    
    for index,triple in enumerate(triplets):
        # Instantiate AI_Hypothesis for the given triple
        triplet = {}
        for i in triplets[triple]:
            if 'XAI' in i:
                continue
            elif 'Papers count' in i:
                continue 
            else:
                triplet[i] =   triplets[triple][i]
        ai_scientist = AI_Hypothesis(
            triplet,
            num_hypothethesis=8,
            save_path=f"Results/AI_Hypothesis/{triplets[triple].get('cancer name')}_{triplets[triple].get('gene name')}_8",
            knowledge_path="data/text-embedding-3-small",
            chatModel='o3-mini',
            embeddingModel='text-embedding-3-small'
        )
        
        champion_hypothesis = asyncio.run(ai_scientist.internal_trial_system())
        print(f"Champion hypothesis for triple {triplets[triple].get('cancer name')}_{triplets[triple].get('gene name')}':\n{champion_hypothesis}\n")
        
if __name__ == '__main__':
    _main()